fn main() {
	let a = 23

	let f = fn(): int {
		a // should be error!
	}

	let b = f()

	print b
}
